import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/auth_provider.dart';
import '../providers/plush_provider.dart';

class JoinPlushScreen extends ConsumerStatefulWidget {
  const JoinPlushScreen({super.key});

  @override
  ConsumerState<JoinPlushScreen> createState() => _JoinPlushScreenState();
}

class _JoinPlushScreenState extends ConsumerState<JoinPlushScreen> {
  final _codeController = TextEditingController();
  bool _isLoading = false;

  Future<void> _join() async {
    setState(() => _isLoading = true);
    final firestore = ref.read(firestoreServiceProvider);
    final authUser = ref.read(authServiceProvider).currentUser;

    if (authUser == null) {
      if (mounted) {
        setState(() => _isLoading = false);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('User not authenticated')),
        );
      }
      return;
    }

    try {
      final plush = await firestore.getPlushByInviteCode(_codeController.text);
      if (plush != null) {
        if (plush.ownerB != null) {
          throw 'This plush already has two owners!';
        }
        
        // Update plush ownerB
        final updatedPlush = plush.copyWith(ownerB: authUser.uid);
        await firestore.updatePlush(updatedPlush);
        
        // Update partnerId for both users
        await firestore.updatePartnerId(authUser.uid, plush.ownerA);
        await firestore.updatePartnerId(plush.ownerA, authUser.uid);
        
        // Update FCM token since now the user has a plush document
        await ref.read(notificationServiceProvider).updateUserFcmToken(authUser.uid);
        
        if (mounted) Navigator.pop(context);
      } else {
        throw 'Invalid invite code';
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e.toString())));
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Join Plush')),
      body: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(
          children: [
            const Text(
              'Enter the 6-digit invite code generated by your partner.',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 32),
            TextField(
              controller: _codeController,
              decoration: const InputDecoration(hintText: 'Invite Code (e.g. 123456)'),
              textAlign: TextAlign.center,
              style: const TextStyle(fontSize: 24, letterSpacing: 8),
              keyboardType: TextInputType.number,
              maxLength: 6,
            ),
            const SizedBox(height: 32),
            _isLoading
                ? const CircularProgressIndicator()
                : ElevatedButton(
                    onPressed: _join,
                    child: const Text('Join My Partner'),
                  ),
          ],
        ),
      ),
    );
  }
}
